// flow-typed signature: 8b171e70285f29a6b8af016f0db82ff9
// flow-typed version: <<STUB>>/box-intersect_v^1.0.2/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'box-intersect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'box-intersect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'box-intersect/lib/brute' {
  declare module.exports: any;
}

declare module 'box-intersect/lib/intersect' {
  declare module.exports: any;
}

declare module 'box-intersect/lib/median' {
  declare module.exports: any;
}

declare module 'box-intersect/lib/partition' {
  declare module.exports: any;
}

declare module 'box-intersect/lib/sort' {
  declare module.exports: any;
}

declare module 'box-intersect/lib/sweep' {
  declare module.exports: any;
}

// Filename aliases
declare module 'box-intersect/index' {
  declare module.exports: $Exports<'box-intersect'>;
}
declare module 'box-intersect/index.js' {
  declare module.exports: $Exports<'box-intersect'>;
}
declare module 'box-intersect/lib/brute.js' {
  declare module.exports: $Exports<'box-intersect/lib/brute'>;
}
declare module 'box-intersect/lib/intersect.js' {
  declare module.exports: $Exports<'box-intersect/lib/intersect'>;
}
declare module 'box-intersect/lib/median.js' {
  declare module.exports: $Exports<'box-intersect/lib/median'>;
}
declare module 'box-intersect/lib/partition.js' {
  declare module.exports: $Exports<'box-intersect/lib/partition'>;
}
declare module 'box-intersect/lib/sort.js' {
  declare module.exports: $Exports<'box-intersect/lib/sort'>;
}
declare module 'box-intersect/lib/sweep.js' {
  declare module.exports: $Exports<'box-intersect/lib/sweep'>;
}
