// flow-typed signature: 04a419a574c5634de56a364e6955b2f7
// flow-typed version: <<STUB>>/react-pixi-fiber_v^1.0.0-beta.1/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-pixi-fiber'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-pixi-fiber' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-pixi-fiber/cjs/react-pixi-alias.development' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/cjs/react-pixi-alias.production.min' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/cjs/react-pixi-fiber.development' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/cjs/react-pixi-fiber.production.min' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/react-pixi-alias' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/src/AppProvider' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/src/compat' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/src/CustomPIXIComponent' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/src/hooks' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/src' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/src/inject' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/src/PixiProperty' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/src/PixiPropertyOperations' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/src/possibleStandardNames' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/src/props' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/src/propTypes' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/src/react-pixi-alias' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/src/ReactGlobalSharedState' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/src/ReactPixiFiber' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/src/ReactPixiFiberComponent' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/src/ReactPixiFiberUnknownPropertyHook' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/src/render' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/src/Stage/common' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/src/Stage/hooks' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/src/Stage' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/src/Stage/legacy' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/src/Stage/propTypes' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/src/types' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/src/utils' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/umd/react-pixi-alias.development' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/umd/react-pixi-alias.production.min' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/umd/react-pixi-fiber.development' {
  declare module.exports: any;
}

declare module 'react-pixi-fiber/umd/react-pixi-fiber.production.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-pixi-fiber/cjs/react-pixi-alias.development.js' {
  declare module.exports: $Exports<'react-pixi-fiber/cjs/react-pixi-alias.development'>;
}
declare module 'react-pixi-fiber/cjs/react-pixi-alias.production.min.js' {
  declare module.exports: $Exports<'react-pixi-fiber/cjs/react-pixi-alias.production.min'>;
}
declare module 'react-pixi-fiber/cjs/react-pixi-fiber.development.js' {
  declare module.exports: $Exports<'react-pixi-fiber/cjs/react-pixi-fiber.development'>;
}
declare module 'react-pixi-fiber/cjs/react-pixi-fiber.production.min.js' {
  declare module.exports: $Exports<'react-pixi-fiber/cjs/react-pixi-fiber.production.min'>;
}
declare module 'react-pixi-fiber/index' {
  declare module.exports: $Exports<'react-pixi-fiber'>;
}
declare module 'react-pixi-fiber/index.js' {
  declare module.exports: $Exports<'react-pixi-fiber'>;
}
declare module 'react-pixi-fiber/react-pixi-alias.js' {
  declare module.exports: $Exports<'react-pixi-fiber/react-pixi-alias'>;
}
declare module 'react-pixi-fiber/src/AppProvider.js' {
  declare module.exports: $Exports<'react-pixi-fiber/src/AppProvider'>;
}
declare module 'react-pixi-fiber/src/compat.js' {
  declare module.exports: $Exports<'react-pixi-fiber/src/compat'>;
}
declare module 'react-pixi-fiber/src/CustomPIXIComponent.js' {
  declare module.exports: $Exports<'react-pixi-fiber/src/CustomPIXIComponent'>;
}
declare module 'react-pixi-fiber/src/hooks.js' {
  declare module.exports: $Exports<'react-pixi-fiber/src/hooks'>;
}
declare module 'react-pixi-fiber/src/index' {
  declare module.exports: $Exports<'react-pixi-fiber/src'>;
}
declare module 'react-pixi-fiber/src/index.js' {
  declare module.exports: $Exports<'react-pixi-fiber/src'>;
}
declare module 'react-pixi-fiber/src/inject.js' {
  declare module.exports: $Exports<'react-pixi-fiber/src/inject'>;
}
declare module 'react-pixi-fiber/src/PixiProperty.js' {
  declare module.exports: $Exports<'react-pixi-fiber/src/PixiProperty'>;
}
declare module 'react-pixi-fiber/src/PixiPropertyOperations.js' {
  declare module.exports: $Exports<'react-pixi-fiber/src/PixiPropertyOperations'>;
}
declare module 'react-pixi-fiber/src/possibleStandardNames.js' {
  declare module.exports: $Exports<'react-pixi-fiber/src/possibleStandardNames'>;
}
declare module 'react-pixi-fiber/src/props.js' {
  declare module.exports: $Exports<'react-pixi-fiber/src/props'>;
}
declare module 'react-pixi-fiber/src/propTypes.js' {
  declare module.exports: $Exports<'react-pixi-fiber/src/propTypes'>;
}
declare module 'react-pixi-fiber/src/react-pixi-alias/index' {
  declare module.exports: $Exports<'react-pixi-fiber/src/react-pixi-alias'>;
}
declare module 'react-pixi-fiber/src/react-pixi-alias/index.js' {
  declare module.exports: $Exports<'react-pixi-fiber/src/react-pixi-alias'>;
}
declare module 'react-pixi-fiber/src/ReactGlobalSharedState.js' {
  declare module.exports: $Exports<'react-pixi-fiber/src/ReactGlobalSharedState'>;
}
declare module 'react-pixi-fiber/src/ReactPixiFiber.js' {
  declare module.exports: $Exports<'react-pixi-fiber/src/ReactPixiFiber'>;
}
declare module 'react-pixi-fiber/src/ReactPixiFiberComponent.js' {
  declare module.exports: $Exports<'react-pixi-fiber/src/ReactPixiFiberComponent'>;
}
declare module 'react-pixi-fiber/src/ReactPixiFiberUnknownPropertyHook.js' {
  declare module.exports: $Exports<'react-pixi-fiber/src/ReactPixiFiberUnknownPropertyHook'>;
}
declare module 'react-pixi-fiber/src/render.js' {
  declare module.exports: $Exports<'react-pixi-fiber/src/render'>;
}
declare module 'react-pixi-fiber/src/Stage/common.js' {
  declare module.exports: $Exports<'react-pixi-fiber/src/Stage/common'>;
}
declare module 'react-pixi-fiber/src/Stage/hooks.js' {
  declare module.exports: $Exports<'react-pixi-fiber/src/Stage/hooks'>;
}
declare module 'react-pixi-fiber/src/Stage/index' {
  declare module.exports: $Exports<'react-pixi-fiber/src/Stage'>;
}
declare module 'react-pixi-fiber/src/Stage/index.js' {
  declare module.exports: $Exports<'react-pixi-fiber/src/Stage'>;
}
declare module 'react-pixi-fiber/src/Stage/legacy.js' {
  declare module.exports: $Exports<'react-pixi-fiber/src/Stage/legacy'>;
}
declare module 'react-pixi-fiber/src/Stage/propTypes.js' {
  declare module.exports: $Exports<'react-pixi-fiber/src/Stage/propTypes'>;
}
declare module 'react-pixi-fiber/src/types.js' {
  declare module.exports: $Exports<'react-pixi-fiber/src/types'>;
}
declare module 'react-pixi-fiber/src/utils.js' {
  declare module.exports: $Exports<'react-pixi-fiber/src/utils'>;
}
declare module 'react-pixi-fiber/umd/react-pixi-alias.development.js' {
  declare module.exports: $Exports<'react-pixi-fiber/umd/react-pixi-alias.development'>;
}
declare module 'react-pixi-fiber/umd/react-pixi-alias.production.min.js' {
  declare module.exports: $Exports<'react-pixi-fiber/umd/react-pixi-alias.production.min'>;
}
declare module 'react-pixi-fiber/umd/react-pixi-fiber.development.js' {
  declare module.exports: $Exports<'react-pixi-fiber/umd/react-pixi-fiber.development'>;
}
declare module 'react-pixi-fiber/umd/react-pixi-fiber.production.min.js' {
  declare module.exports: $Exports<'react-pixi-fiber/umd/react-pixi-fiber.production.min'>;
}
