// flow-typed signature: 8d91a9542e45cb89d5e81272df1e6da0
// flow-typed version: <<STUB>>/react-entity-component-system_v^2.0.0/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-entity-component-system'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-entity-component-system' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-entity-component-system/dist' {
  declare module.exports: any;
}

declare module 'react-entity-component-system/src/Debug' {
  declare module.exports: any;
}

declare module 'react-entity-component-system/src/helpers/defaultInitializeEntities' {
  declare module.exports: any;
}

declare module 'react-entity-component-system/src/helpers/defaultRenderEntities' {
  declare module.exports: any;
}

declare module 'react-entity-component-system/src/helpers/defaultUniqueId' {
  declare module.exports: any;
}

declare module 'react-entity-component-system/src/helpers/hasAllKeys' {
  declare module.exports: any;
}

declare module 'react-entity-component-system/src/helpers/useConsoleWarnIfInvokedTooManyRendersInARow' {
  declare module.exports: any;
}

declare module 'react-entity-component-system/src/helpers/useRenderCount' {
  declare module.exports: any;
}

declare module 'react-entity-component-system/src' {
  declare module.exports: any;
}

declare module 'react-entity-component-system/src/useEntityComponentSystem' {
  declare module.exports: any;
}

declare module 'react-entity-component-system/src/useGameEvents' {
  declare module.exports: any;
}

declare module 'react-entity-component-system/src/useGameLoop' {
  declare module.exports: any;
}

declare module 'react-entity-component-system/src/useKeysDown' {
  declare module.exports: any;
}

declare module 'react-entity-component-system/stories/basic/0-Basic-ECS.stories' {
  declare module.exports: any;
}

declare module 'react-entity-component-system/stories/basic/BasicECS' {
  declare module.exports: any;
}

declare module 'react-entity-component-system/stories/basic/Events' {
  declare module.exports: any;
}

declare module 'react-entity-component-system/stories/basic/Looping' {
  declare module.exports: any;
}

declare module 'react-entity-component-system/stories/basic/Swapping' {
  declare module.exports: any;
}

declare module 'react-entity-component-system/stories/breakout/1-Breakout.stories' {
  declare module.exports: any;
}

declare module 'react-entity-component-system/stories/breakout/GameWindow' {
  declare module.exports: any;
}

declare module 'react-entity-component-system/stories/breakout/initialEntities' {
  declare module.exports: any;
}

declare module 'react-entity-component-system/stories/breakout/initializeSystems' {
  declare module.exports: any;
}

declare module 'react-entity-component-system/stories/breakout/renderers/Ball' {
  declare module.exports: any;
}

declare module 'react-entity-component-system/stories/breakout/renderers/Block' {
  declare module.exports: any;
}

declare module 'react-entity-component-system/stories/breakout/renderers' {
  declare module.exports: any;
}

declare module 'react-entity-component-system/stories/breakout/renderers/Paddle' {
  declare module.exports: any;
}

declare module 'react-entity-component-system/stories/breakout/renderers/Score' {
  declare module.exports: any;
}

declare module 'react-entity-component-system/stories/breakout/renderers/WinMessage' {
  declare module.exports: any;
}

declare module 'react-entity-component-system/stories/breakout/systems/ballCollisionSystem' {
  declare module.exports: any;
}

declare module 'react-entity-component-system/stories/breakout/systems/blockHitSystem' {
  declare module.exports: any;
}

declare module 'react-entity-component-system/stories/breakout/systems/collisionSystem' {
  declare module.exports: any;
}

declare module 'react-entity-component-system/stories/breakout/systems' {
  declare module.exports: any;
}

declare module 'react-entity-component-system/stories/breakout/systems/movementSystem' {
  declare module.exports: any;
}

declare module 'react-entity-component-system/stories/breakout/systems/paddleMovementSystem' {
  declare module.exports: any;
}

declare module 'react-entity-component-system/stories/breakout/systems/scoreSystem' {
  declare module.exports: any;
}

declare module 'react-entity-component-system/stories/breakout/systems/wallCollisionSystem' {
  declare module.exports: any;
}

declare module 'react-entity-component-system/stories/breakout/systems/winSystem' {
  declare module.exports: any;
}

declare module 'react-entity-component-system/stories/breakout/useClickToStart' {
  declare module.exports: any;
}

declare module 'react-entity-component-system/stories/helpers/Code' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-entity-component-system/dist/index' {
  declare module.exports: $Exports<'react-entity-component-system/dist'>;
}
declare module 'react-entity-component-system/dist/index.js' {
  declare module.exports: $Exports<'react-entity-component-system/dist'>;
}
declare module 'react-entity-component-system/src/Debug.jsx' {
  declare module.exports: $Exports<'react-entity-component-system/src/Debug'>;
}
declare module 'react-entity-component-system/src/helpers/defaultInitializeEntities.js' {
  declare module.exports: $Exports<'react-entity-component-system/src/helpers/defaultInitializeEntities'>;
}
declare module 'react-entity-component-system/src/helpers/defaultRenderEntities.jsx' {
  declare module.exports: $Exports<'react-entity-component-system/src/helpers/defaultRenderEntities'>;
}
declare module 'react-entity-component-system/src/helpers/defaultUniqueId.js' {
  declare module.exports: $Exports<'react-entity-component-system/src/helpers/defaultUniqueId'>;
}
declare module 'react-entity-component-system/src/helpers/hasAllKeys.js' {
  declare module.exports: $Exports<'react-entity-component-system/src/helpers/hasAllKeys'>;
}
declare module 'react-entity-component-system/src/helpers/useConsoleWarnIfInvokedTooManyRendersInARow.js' {
  declare module.exports: $Exports<'react-entity-component-system/src/helpers/useConsoleWarnIfInvokedTooManyRendersInARow'>;
}
declare module 'react-entity-component-system/src/helpers/useRenderCount.js' {
  declare module.exports: $Exports<'react-entity-component-system/src/helpers/useRenderCount'>;
}
declare module 'react-entity-component-system/src/index' {
  declare module.exports: $Exports<'react-entity-component-system/src'>;
}
declare module 'react-entity-component-system/src/index.js' {
  declare module.exports: $Exports<'react-entity-component-system/src'>;
}
declare module 'react-entity-component-system/src/useEntityComponentSystem.js' {
  declare module.exports: $Exports<'react-entity-component-system/src/useEntityComponentSystem'>;
}
declare module 'react-entity-component-system/src/useGameEvents.js' {
  declare module.exports: $Exports<'react-entity-component-system/src/useGameEvents'>;
}
declare module 'react-entity-component-system/src/useGameLoop.js' {
  declare module.exports: $Exports<'react-entity-component-system/src/useGameLoop'>;
}
declare module 'react-entity-component-system/src/useKeysDown.js' {
  declare module.exports: $Exports<'react-entity-component-system/src/useKeysDown'>;
}
declare module 'react-entity-component-system/stories/basic/0-Basic-ECS.stories.js' {
  declare module.exports: $Exports<'react-entity-component-system/stories/basic/0-Basic-ECS.stories'>;
}
declare module 'react-entity-component-system/stories/basic/BasicECS.jsx' {
  declare module.exports: $Exports<'react-entity-component-system/stories/basic/BasicECS'>;
}
declare module 'react-entity-component-system/stories/basic/Events.jsx' {
  declare module.exports: $Exports<'react-entity-component-system/stories/basic/Events'>;
}
declare module 'react-entity-component-system/stories/basic/Looping.jsx' {
  declare module.exports: $Exports<'react-entity-component-system/stories/basic/Looping'>;
}
declare module 'react-entity-component-system/stories/basic/Swapping.jsx' {
  declare module.exports: $Exports<'react-entity-component-system/stories/basic/Swapping'>;
}
declare module 'react-entity-component-system/stories/breakout/1-Breakout.stories.js' {
  declare module.exports: $Exports<'react-entity-component-system/stories/breakout/1-Breakout.stories'>;
}
declare module 'react-entity-component-system/stories/breakout/GameWindow.jsx' {
  declare module.exports: $Exports<'react-entity-component-system/stories/breakout/GameWindow'>;
}
declare module 'react-entity-component-system/stories/breakout/initialEntities.js' {
  declare module.exports: $Exports<'react-entity-component-system/stories/breakout/initialEntities'>;
}
declare module 'react-entity-component-system/stories/breakout/initializeSystems.js' {
  declare module.exports: $Exports<'react-entity-component-system/stories/breakout/initializeSystems'>;
}
declare module 'react-entity-component-system/stories/breakout/renderers/Ball.jsx' {
  declare module.exports: $Exports<'react-entity-component-system/stories/breakout/renderers/Ball'>;
}
declare module 'react-entity-component-system/stories/breakout/renderers/Block.jsx' {
  declare module.exports: $Exports<'react-entity-component-system/stories/breakout/renderers/Block'>;
}
declare module 'react-entity-component-system/stories/breakout/renderers/index' {
  declare module.exports: $Exports<'react-entity-component-system/stories/breakout/renderers'>;
}
declare module 'react-entity-component-system/stories/breakout/renderers/index.js' {
  declare module.exports: $Exports<'react-entity-component-system/stories/breakout/renderers'>;
}
declare module 'react-entity-component-system/stories/breakout/renderers/Paddle.jsx' {
  declare module.exports: $Exports<'react-entity-component-system/stories/breakout/renderers/Paddle'>;
}
declare module 'react-entity-component-system/stories/breakout/renderers/Score.jsx' {
  declare module.exports: $Exports<'react-entity-component-system/stories/breakout/renderers/Score'>;
}
declare module 'react-entity-component-system/stories/breakout/renderers/WinMessage.jsx' {
  declare module.exports: $Exports<'react-entity-component-system/stories/breakout/renderers/WinMessage'>;
}
declare module 'react-entity-component-system/stories/breakout/systems/ballCollisionSystem.js' {
  declare module.exports: $Exports<'react-entity-component-system/stories/breakout/systems/ballCollisionSystem'>;
}
declare module 'react-entity-component-system/stories/breakout/systems/blockHitSystem.js' {
  declare module.exports: $Exports<'react-entity-component-system/stories/breakout/systems/blockHitSystem'>;
}
declare module 'react-entity-component-system/stories/breakout/systems/collisionSystem.js' {
  declare module.exports: $Exports<'react-entity-component-system/stories/breakout/systems/collisionSystem'>;
}
declare module 'react-entity-component-system/stories/breakout/systems/index' {
  declare module.exports: $Exports<'react-entity-component-system/stories/breakout/systems'>;
}
declare module 'react-entity-component-system/stories/breakout/systems/index.js' {
  declare module.exports: $Exports<'react-entity-component-system/stories/breakout/systems'>;
}
declare module 'react-entity-component-system/stories/breakout/systems/movementSystem.js' {
  declare module.exports: $Exports<'react-entity-component-system/stories/breakout/systems/movementSystem'>;
}
declare module 'react-entity-component-system/stories/breakout/systems/paddleMovementSystem.js' {
  declare module.exports: $Exports<'react-entity-component-system/stories/breakout/systems/paddleMovementSystem'>;
}
declare module 'react-entity-component-system/stories/breakout/systems/scoreSystem.js' {
  declare module.exports: $Exports<'react-entity-component-system/stories/breakout/systems/scoreSystem'>;
}
declare module 'react-entity-component-system/stories/breakout/systems/wallCollisionSystem.js' {
  declare module.exports: $Exports<'react-entity-component-system/stories/breakout/systems/wallCollisionSystem'>;
}
declare module 'react-entity-component-system/stories/breakout/systems/winSystem.js' {
  declare module.exports: $Exports<'react-entity-component-system/stories/breakout/systems/winSystem'>;
}
declare module 'react-entity-component-system/stories/breakout/useClickToStart.js' {
  declare module.exports: $Exports<'react-entity-component-system/stories/breakout/useClickToStart'>;
}
declare module 'react-entity-component-system/stories/helpers/Code.jsx' {
  declare module.exports: $Exports<'react-entity-component-system/stories/helpers/Code'>;
}
