// flow-typed signature: 12785835f428dd1b79002b048a217ab7
// flow-typed version: <<STUB>>/secure-electron-store_v^1.0.1/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'secure-electron-store'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'secure-electron-store' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'secure-electron-store/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'secure-electron-store/lib/index' {
  declare module.exports: $Exports<'secure-electron-store/lib'>;
}
declare module 'secure-electron-store/lib/index.js' {
  declare module.exports: $Exports<'secure-electron-store/lib'>;
}
