// flow-typed signature: 08a8eff3912abb7e3426d24d9e8f3c8a
// flow-typed version: <<STUB>>/vec-la-fp_v^1.9.0/flow_v0.118.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'vec-la-fp'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'vec-la-fp' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'vec-la-fp/dist/vec.module' {
  declare module.exports: any;
}

declare module 'vec-la-fp/gulpfile' {
  declare module.exports: any;
}

declare module 'vec-la-fp/tests/vec.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'vec-la-fp/dist/vec.module.js' {
  declare module.exports: $Exports<'vec-la-fp/dist/vec.module'>;
}
declare module 'vec-la-fp/gulpfile.js' {
  declare module.exports: $Exports<'vec-la-fp/gulpfile'>;
}
declare module 'vec-la-fp/tests/vec.test.js' {
  declare module.exports: $Exports<'vec-la-fp/tests/vec.test'>;
}
